on: push
name: Release Build
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BT_DIR: ${{ github.workspace }}/BATTLETECH
      CC_DIR: ${{ github.workspace }}/CustomComponents
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '6.0.x'
    - name: Download Build Dependencies
      env:
        MANAGED_ARCHIVE_PW: ${{ secrets.MANAGED_ARCHIVE_PW }}
        MANAGED_ARCHIVE_URL: ${{ secrets.MANAGED_ARCHIVE_URL }}
      run: |
        # BattleTech Managed
        curl -L -o "$GITHUB_WORKSPACE/Managed.7z" "$MANAGED_ARCHIVE_URL"
        MANAGED_DIR="$BT_DIR/BattleTech_Data/Managed"
        mkdir -p "$MANAGED_DIR"
        7z e -p"$MANAGED_ARCHIVE_PW" -o"$MANAGED_DIR" "$GITHUB_WORKSPACE/Managed.7z"
    - name: Checkout
      uses: actions/checkout@master
      with:
        path: ${{ env.CC_DIR }}
    - name: Fetch Branches and Tags
      run: cd "$CC_DIR" && git fetch --prune --unshallow
    - name: Build Release
      run: cd "$CC_DIR" && ./release.sh "-p:BattleTechGameDir=$BT_DIR"
    - name: Release Latest
      uses: "marvinpinto/action-automatic-releases@latest"
      if: github.ref == 'refs/heads/main'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest (unstable)"
        prerelease: true
        files: |
          ./CustomComponents/dist/CustomComponents.zip
    - name: Release stable
      uses: "softprops/action-gh-release@master"
      if: startsWith(github.ref, 'refs/tags')
      with:
        draft: false
        prerelease: false
        body: |
          Works with best with ModTek v2
          - CustomComponents.zip contains the compiled framework
        files: "./CustomComponents/dist/CustomComponents.zip"
