on: push
name: Release Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '6.0.x'
    - name: Download Build Dependencies
      shell: bash
      env:
        MANAGED_ARCHIVE_PW: ${{ secrets.MANAGED_ARCHIVE_PW }}
        MANAGED_ARCHIVE_URL: ${{ secrets.MANAGED_ARCHIVE_URL }}
      run: |
        set -e
        curl -L -o "$GITHUB_WORKSPACE/Managed.7z" "$MANAGED_ARCHIVE_URL"
        7z e -p"$MANAGED_ARCHIVE_PW" -o"$GITHUB_WORKSPACE/deps" "$GITHUB_WORKSPACE/Managed.7z"
    - name: Checkout CustomComponents
      uses: actions/checkout@master
      with:
        path: CustomComponents/
    - name: Fetch CustomComponents Branches and Tags
      shell: bash
      run: |
        cd CustomComponents/
        git fetch --prune --unshallow
    - name: Build Release
      shell: bash
      env:
        MSBUILDSINGLELOADCONTEXT: 1 # workaround for GitVersionTask
      run: |
        set -e
        cd "$GITHUB_WORKSPACE/CustomComponents/"
        ./release.sh "-p:ReferencePath=$GITHUB_WORKSPACE/deps"
    - name: Tag latest
      shell: bash
      if: github.ref == 'refs/heads/UnitTypes'
      run: |
        cd CustomComponents/
        git tag -f latest
        git push -f origin refs/tags/latest
    - name: Release latest
      uses: "softprops/action-gh-release@master"
      if: github.ref == 'refs/heads/UnitTypes'
      with:
        draft: false
        prerelease: true
        name: "Latest (unstable)"
        tag_name: "latest"
        body: |
          Latest unstable release, even less tested than normal releases.
          Works with best with ModTek v2
          - CustomComponents.zip contains the compiled framework
        files: "./CustomComponents/dist/CustomComponents.zip"
    - name: Release stable
      uses: "softprops/action-gh-release@master"
      if: startsWith(github.ref, 'refs/tags')
      with:
        draft: false
        prerelease: false
        body: |
          Works with best with ModTek v2
          - CustomComponents.zip contains the compiled framework
        files: "./CustomComponents/dist/CustomComponents.zip"
