on: push
name: CI

jobs:
  build:
    uses: BattletechModders/ModTek/.github/workflows/mod-builder.yml@master
    with:
      checkout-directory: 'BATTLETECH/Mods/CustomComponents'
      build-script: |
        (
          cd source
          dotnet build -c Release -p:BattleTechGameDir="$BATTLETECH_DIR/"
        )
        (
          cd ..
          7z a -tzip -mx9 "$DIST_DIR/CustomComponents.zip" \
            -ir!CustomComponents \
            -xr!CCTestMod \
            -xr!source "-xr!.*"
        )
      release-notes: |
        Works best with ModTek V3
        - CustomComponents.zip contains the compiled framework
    secrets: inherit
